export const refs = {
  modal: document.querySelector('[data-modal]'),
  filmsEl: document.querySelector('.films'),
  searchFormEl: document.querySelector('.header__form'),
  inputBtnEl: document.querySelector('.js-input-btn'),
  homeBtn: document.querySelector(['[data-action="home"]']),
  libraryBtn: document.querySelector('[data-action="library"]'),
  headerBtn: document.querySelector('.header__btn'),
  header: document.querySelector('.header'),
  headerNav: document.querySelector('.header__nav'),
  watchedBtn: document.querySelector('[data-action="watched"]'),
  queueBtn: document.querySelector('[data-action="queue"]'),
  openModalBtn: document.querySelector('[data-modal-open]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  backdrop: document.querySelector('.backdrop'),
  logo: document.querySelector('.js-logo'),
  headerInputField: document.querySelector('.header__form > input'),
};
